<?php
/**
 * Generated by grunt-phpclassmap on {{date}}
 */

{{#if quote_path}}
// With quote
{{/if}}
return array(
{{#foreach items}}
    "{{name}}" => {{#if ../quote_path}}"{{/if}}{{{relative_path}}}{{#if ../quote_path}}"{{/if}}{{#unless $last}},{{/unless}}
{{/foreach}}
);

/* EOF */